apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: acme-fitness.external.demo-dependencies.learn.1.0.1
spec:
  refName: acme-fitness.external.demo-dependencies.learn
  version: 1.0.1
  releaseNotes: |
    Page release of the acme-fitness package, changing products to include AI capabilities.
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        namespace:
          type: string
          description: Namespace to deploy
          default: app-acme-fitness
        fqdn:
          type: string
          description: FQDN
          default: acme-fitness.foo.org
  template:
    spec:
      fetch:
      - git:
          url: https://github.com/bkirkware/acme-fitness-package-repo
          ref: origin/main
          subPath: packages/acme-fitness/1.0.1/bundle
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
